export const mockBookings = [
  {
    bookingId: "BK-1001",
    patientName: "Manoj Tamang",
    hospitalName: "City Care Hospital",
    bedType: "ICU",
    bookingDate: "2024-03-01",
    admissionDate: "2024-03-01",
    dischargeDate: "2024-03-05",
    status: "Completed",
    paymentStatus: "Paid",
    amount: 45000,
    bookingSource: "App"
  },
  {
    bookingId: "BK-1002",
    patientName: "Jane Smith",
    hospitalName: "City Care Hospital",
    bedType: "General",
    bookingDate: "2024-03-04",
    admissionDate: "2024-03-04",
    dischargeDate: "2024-03-06",
    status: "Active",
    paymentStatus: "Pending",
    amount: 15000,
    bookingSource: "Admin"
  },
  {
    bookingId: "BK-1003",
    patientName: "Hari Rai",
    hospitalName: "City Care Hospital",
    bedType: "Emergency",
    bookingDate: "2024-03-02",
    admissionDate: "2024-03-02",
    dischargeDate: "-",
    status: "Cancelled",
    paymentStatus: "Refunded",
    amount: 5000,
    bookingSource: "Emergency Desk"
  },
  {
    bookingId: "BK-1004",
    patientName: "Ram Yadav",
    hospitalName: "City Care Hospital",
    bedType: "ICU",
    bookingDate: "2024-02-28",
    admissionDate: "2024-02-28",
    dischargeDate: "2024-03-04",
    status: "Completed",
    paymentStatus: "Paid",
    amount: 55000,
    bookingSource: "App"
  },
  {
    bookingId: "BK-1005",
    patientName: "Riya Tamang",
    hospitalName: "City Care Hospital",
    bedType: "Maternity",
    bookingDate: "2024-03-05",
    admissionDate: "2024-03-05",
    dischargeDate: "2024-03-08",
    status: "Active",
    paymentStatus: "Paid",
    amount: 25000,
    bookingSource: "Admin"
  },
  {
    bookingId: "BK-1006",
    patientName: "Sara Khan",
    hospitalName: "City Care Hospital",
    bedType: "General",
    bookingDate: "2024-02-25",
    admissionDate: "2024-02-25",
    dischargeDate: "2024-02-27",
    status: "Completed",
    paymentStatus: "Paid",
    amount: 12000,
    bookingSource: "App"
  },
  {
    bookingId: "BK-1007",
    patientName: "Tom Hardy",
    hospitalName: "City Care Hospital",
    bedType: "ICU",
    bookingDate: "2024-03-06",
    admissionDate: "2024-03-06",
    dischargeDate: "2024-03-10",
    status: "Active",
    paymentStatus: "Pending",
    amount: 60000,
    bookingSource: "Emergency Desk"
  },
  {
    bookingId: "BK-1008",
    patientName: "Lisa Ray",
    hospitalName: "City Care Hospital",
    bedType: "General",
    bookingDate: "2024-03-03",
    admissionDate: "2024-03-03",
    dischargeDate: "-",
    status: "Cancelled",
    paymentStatus: "Refunded",
    amount: 3000,
    bookingSource: "App"
  }
];
